service: serverless

provider:
  name: aws
  runtime: nodejs12.x
  stage: default
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - lambda:InvokeFunction
      Resource: "*"

functions:
  fetchProducts:
    handler: fetchProducts.fetchProducts
  fetchShop:
    handler: fetchShop.fetchShop
  saveAccessToken:
    handler: saveAccessToken.saveAccessToken
  validateSessionToken:
    handler: validateSessionToken.validateSessionToken

plugins:
 - serverless-dynamodb-local
 - serverless-offline

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      development:
        sources:
          - table: Shop
            sources: [./migrations/shop.json]
    stages:
      - default

resources:
  Resources:
    Shop:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Shop
        AttributeDefinitions:
          - AttributeName: shopName
            AttributeType: S
        KeySchema:
          - AttributeName: shopName
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
